apiVersion: v1
kind: Service
metadata:
  name: flask-web-app
spec:
  selector:
    app: flask-web-app
  ports:
    - protocol: TCP
      port: 5000      
      targetPort: 5000  # Pod içindeki uygulama portu
      nodePort: 30000   # Minikube dışa açılacak port
  type: NodePort
